// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.166
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenPromptHere
{
    static class Vsix
    {
        public const string Id = "OpenPromptHere.SpringComp";
        public const string Name = "Open PowerShell Prompt";
        public const string Description = "Open a PowerShell command prompt at the target location of the selected project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "SpringComp";
        public const string Tags = "Command Prompt, PowerShell";
    }
}
